CREATE OR REPLACE PACKAGE PKG_JSON AS
    FUNCTION GET_JSON(p_first NUMBER DEFAULT 1, p_table VARCHAR2, p_where VARCHAR2 DEfAULT NULL) RETURN CLOB;
    FUNCTION BUILD_STRING_ARRAY(p_line VARCHAR2) RETURN CLOB;
END PKG_JSON;
/