create or replace PACKAGE PKG_JSON AS
    FUNCTION GET_JSON(p_table VARCHAR2, p_where VARCHAR2 DEfAULT NULL) RETURN CLOB;
    FUNCTION GET_JSON_SUB(p_first NUMBER, p_table VARCHAR2, p_where VARCHAR2 DEfAULT NULL) RETURN CLOB;
    FUNCTION STRING_ARRAY(p_line VARCHAR2) RETURN CLOB;
END PKG_JSON;