CREATE OR REPLACE PACKAGE SHPK_JSON AS
    FUNCTION SHF_GET_JSON(p_first NUMBER DEFAULT 1, p_table VARCHAR2, p_where VARCHAR2 DEfAULT NULL) RETURN CLOB;
    FUNCTION SHF_STRING_ARRAY(p_line VARCHAR2) RETURN CLOB;
END SHPK_JSON;
/